apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    application: helloworld
  name: helloworld
spec:
  output:
    to:
      kind: ImageStreamTag
      name: helloworld:latest
  source:
    git:
      ref: "master"
      uri: "git@github.com:TimVerbois/openshift_arg_deployments.git"
    type: Git
    sourceSecret:
      name: github
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: eap71-openshift:latest
        namespace: timv-dev
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
