apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    application: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: ${APPLICATION_NAME}:latest
  source:
    git:
      ref: "master"
      uri: "git@212.113.90.91:openshift/ARG_testDeploymentFlows.git"
    type: Git
    sourceSecret:
      name: gitlab
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: eap71-openshift:latest
        namespace: ${NAMESPACE}
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
