apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}
  namespace: ci00000000-argentatest-01
spec:
  replicas: 1
  selector:
    deploymentConfig: ${APPLICATION_NAME}
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        application: ${APPLICATION_NAME}
       deploymentConfig: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      containers:
      - env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: OPENSHIFT_KUBE_PING_LABELS
          value: application=${APPLICATION_NAME}
        - name: OPENSHIFT_KUBE_PING_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HORNETQ_CLUSTER_PASSWORD
          value: kJZLvfQr3hZg
        - name: JGROUPS_CLUSTER_PASSWORD
          value: kJZLvfQr3hZg
        image: ${APPLICATION_NAME}:${VERSION}
        imagePullPolicy: Always
        name: ${APPLICATION_NAME}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      terminationGracePeriodSeconds: 60
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - ${APPLICATION_NAME}
      from:
        kind: ImageStream
        name: ${APPLICATION_NAME}
    type: ImageChange
  - type: ConfigChange
