apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    application: helloworld
  name: helloworld
  namespace: ci00000000-argentatest-01
spec:
  host: helloworld-ci00000000-argentatest-01.apps.openshift.cegeka.com
  to:
    kind: Service
    name: ${APPLICATION_NAME}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - host: helloworld-ci00000000-argentatest-01.apps.openshift.cegeka.com
      routerName: router
      wildcardPolicy: None

